name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-06"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODViNGY1YzUtZDE2ZS00MDk3LWE5NDAtNWVkMTllNDQ2ZDMwIiwidGVuYW50X2lkIjoiNzE0ZjhlMmExNzU1YjNmOTMzMjRkZWZlMGRjMTZkYTg1ZGY3NzlhNTE1NWZlNDc2ZTVjNTkyMjJmNjFjNzNiZiIsImludGVybmFsX3NlY3JldCI6ImY5ZTdhM2ExLWIyY2UtNDk0NS05OGUzLTE1MTNmNGU3ODM5NiJ9.cJPXEOvnMcDW1yTzKalpqY8jLzlrm5pq32A8vteKTK0"
JWT_SECERET = "kyu_janna_hai?"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1